# Generated by Django 6.0.6 on 2026-06-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("navigation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="image",
            field=models.URLField(blank=True),
        ),
    ]
