# Generated by Django 6.0.6 on 2026-06-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("navigation", "0002_store_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
